services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ulinha2003
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rooms-service:
    build: /backend/rooms-service 
    container_name: rooms_service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=P@ulinha2003
    depends_on:
      db:
        condition: service_healthy

  bookings-service:
    build: /backend/bookings-service
    container_name: bookings_service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=P@ulinha2003
    depends_on:
      db:
        condition: service_healthy

  api-gateway:
    build: /backend/api-gateway
    container_name: api_gateway
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=P@ulinha2003    
    depends_on:
      db:
        condition: service_healthy
      rooms-service:
        condition: service_started
      bookings-service:
        condition: service_started

  back-for-front:
    build: /backend/back-for-front
    container_name: back_for_front
    ports:
      - "3003:3003"
    depends_on:
      api-gateway:
        condition: service_started

volumes:
  postgres_data: