sonar.projectKey=Katrina_trabalho-microsservico
sonar.organization=seu-organization-aqui

sonar.sources=backend
sonar.tests=backend

sonar.exclusions=**/node_modules/**,**/coverage/**,**/package-lock.json,**/swagger.json,**/*.html,**/*.css,**/frontend/**

sonar.test.inclusions=**/*.test.js

sonar.coverage.exclusions=**/server.js,**/swagger.json,**/routes/**,**/middlewares/metricsMiddleware.js,**/database/**,**/models/**

sonar.javascript.lcov.reportPaths=backend/api-gateway/coverage/lcov.info,backend/bookings-service/coverage/lcov.info,backend/rooms-service/coverage/lcov.info,backend/back-for-front/coverage/lcov.info