apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: trabalho-microsservico
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: devops_postgres_password
  POSTGRES_DB: postgres
