apiVersion: v1
kind: Secret
metadata:
  name: bookings-service-secret
  namespace: trabalho-microsservico
type: Opaque
stringData:
  JWT_SECRET: devops_jwt_secret
  DATABASE_URL: postgresql://postgres:devops_postgres_password@postgres:5432/postgres
